apiVersion: v1 
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod # apontamento do que ele deve usar
  ports:
    - port: 9000 # Ouve na porta 9000
      targetPort: 80 # Porta que envia o serviço 