apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserver
spec:
  replicas: 3
  selector: # seleciona pyserver
    matchLabels:
      app: pyserver
  template:
    metadata:
      labels:
        app: pyserver
    spec:
      containers:
      - name: pyserver
        image: "faelk8/hello-py:latest"