apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pyserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyserver
  template:
    metadata:
      labels:
        app: pyserver
    spec:
      containers:
      - name: pyserver
        image: "faelk8/hello-py:v2"