apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler 
metadata:
  name: hpa-portal-noticias
spec:
  minReplicas: 1
  maxReplicas: 10
  
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet 
    name: statefulset-portal-noticias
  
  metrics:
    - type: Resource 
      resource:
        name: cpu 
        target: 
          type: Utilization
          averageUtilization: 50 # %