apiVersion: v1 
kind: Pod 
metadata: 
  name: pod-pv
spec:
  containers:
    - name: nginx-containers
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-pv
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: persistent-volume-clain
