apiVersion: v1
kind: Service
metadata:
  name: python-server
spec:
  selector:
    app: server
  type: ClusterIP
  ports:
    - name: server-porta
      port: 80
      targetPort: 8000
      protocol: TCP