apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    name: airflow

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/dags"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-claim
  namespace: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/logs"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-claim
  namespace: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-data-claim
  namespace: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

