apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: faelk8/hello-go:1.7

          startupProbe:
            httpGet:
              path: /healthz
              port: 9000
            periodSeconds: 3
            failureThreshold: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: 9000
            periodSeconds: 3
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /healthz
              port: 9000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
              
          envFrom:
            - configMapRef:
                name: env-goserver
            - secretRef:
                name: secret-goserver

          volumeMounts:
            - mountPath: "/go/redessocias"
              name: config
      volumes:
        - name: config
          configMap: 
            name: configmap-redes-sociais
            items:
            - key: members
              path: "redessocias.txt"
