apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: faelk8/hello-go:v1.3
          envFrom:
            - configMapRef:
                name: env-goserver
          volumeMounts:
            - mountPath: "/go/redessocias"
              name: config
      volumes:
        - name: config
          configMap: 
            name: env-goserver-redes-socias
            items:
            - key: members
              path: "redessocias.txt"
