apiVersion: v1
kind: Service
metadata:
  name: service-goserver
spec:
  replicas: 3
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-service
    port: 9000
    targetPort: 9000
    protocol: TCP